# Site
name: "Yetics"
title: "Yetics"
description: "Yetics Consulting"
meta_description: "Jekyll theme for blogging."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/'
email: 'tech@yetics.com'
google_analytics: 'UA-46278016-1'
disqus: 'yetics'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  andreas:
    name: Andreas
    display_name: Sal
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: tech@yetics.com
    web: https://yetics.github.io/category/jekyll-themes/
    twitter: https://twitter.com/yetics
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  robert:
    name: Robert
    display_name: John
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: tech@yetics.com
    web: https://yetics.github.io/category/jekyll-themes/
    twitter: https://twitter.com/yetics
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge